fit:
  seed_everything: null
  trainer:
    logger:
      class_path: pytorch_lightning.loggers.wandb.WandbLogger
      init_args:
        project: count
    checkpoint_callback: null
    enable_checkpointing: true
    callbacks:
      - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
        init_args:
          monitor: semantic_test_cases
          dirpath: /root/scratch/griffon/count/checkpoints
          filename: sample-count-{epoch:02d}-{semantic_test_cases:.4f}-{validation_top_3:.3f}
          save_top_k: 3
          mode: max
    default_root_dir: null
    gradient_clip_val: null
    gradient_clip_algorithm: null
    process_position: 0
    num_nodes: 1
    num_processes: 1
    devices: null
    gpus: 2
    auto_select_gpus: false
    tpu_cores: null
    ipus: null
    log_gpu_memory: null
    progress_bar_refresh_rate: null
    enable_progress_bar: true
    overfit_batches: 0.0
    track_grad_norm: -1
    check_val_every_n_epoch: 1
    fast_dev_run: false
    accumulate_grad_batches: 4
    max_epochs: 50
    min_epochs: null
    max_steps: -1
    min_steps: null
    max_time: null
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    limit_predict_batches: 1.0
    val_check_interval: 1.0
    flush_logs_every_n_steps: null
    log_every_n_steps: 50
    accelerator: null
    strategy: null
    sync_batchnorm: false
    precision: 32
    enable_model_summary: true
    weights_summary: top
    weights_save_path: null
    num_sanity_val_steps: 2
    resume_from_checkpoint: null
    profiler: null
    benchmark: false
    deterministic: false
    reload_dataloaders_every_n_epochs: 0
    reload_dataloaders_every_epoch: false
    auto_lr_find: false
    replace_sampler_ddp: true
    detect_anomaly: false
    auto_scale_batch_size: false
    prepare_data_per_node: null
    plugins: null
    amp_backend: native
    amp_level: null
    move_metrics_to_cpu: false
    multiple_trainloader_mode: max_size_cycle
    stochastic_weight_avg: false
    terminate_on_nan: null
  model:
    class_path: griffon.models.encoder.count.CounT
    init_args:
      learning_rate: 0.0003
      config:
        architecture:
          pretrained_embeddings_path: /root/scratch/griffon/data/base/stage2/embeddings.pkl
          vocab_file: /root/scratch/griffon/data/base/stage2/vocab.pkl
          subtoken_embedding_dim: 512
          num_subtokens: 5
          token_embedding_dim: 1024
          scale_token_embeddings: false
          activation_fn: tanh
          code_transformer:
            num_layers: 4
            encoder_layer :
              nhead: 8
              dim_feedforward: 2048
              num_relative_distances: 4
            norm:
              type: layer_norm
              eps: 1.e-5
        optimizer:
          loss_fn:
            type: f_loss
            gamma: 2
          lr: 0.1
          warmup_steps: 4000

  data:
    class_path: griffon.dataset.count_datamodule.CounTDataModule
    init_args:
      data_root: /root/scratch/griffon/data
      batch_size: 200
      num_workers: 16

  ckpt_path: null
